name: Addon build
run-name: Building addon
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 ffmpeg
      
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Linux
        run: |
          scons -j4 target=template_debug platform=linux arch=x86_64 compile_ffmpeg=true dev_build=yes
          scons -j4 target=template_release platform=linux arch=x86_64 compile_ffmpeg=false

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GDE_GoZen_Linux
          path: bin/linux/
          retention-days: 1

